// src/routes/api/ai-learning-insight.ts
//
// Backs the "AI Insight" card on the Learning tab (student/parent) and
// teacher analytics panel. Spec §21-23: the AI must combine ERP (official
// results) + Learning (mastery/revision) data and may only ever *describe*
// or *recommend* — never write to exam_results or any official record.
//
// That read-only guarantee is structural, not just prompt discipline: this
// route never writes to the database at all. It calls the single
// SECURITY DEFINER RPC learning_ai_context(_student_id), which is itself
// SELECT-only (see the corrected-architecture migration, §9 "structural
// proof" block that fails the migration if any learning_* function ever
// writes to exam_results/exams), then hands that JSON to Claude purely to
// turn it into readable prose + suggested next steps. There is no code
// path here that can touch official marks.
//
// Authorization is enforced by learning_ai_context() itself (student /
// linked parent / teaching staff of that school / admin / platform admin)
// using the caller's own auth.uid() — this route forwards the user's
// bearer token via requireSupabaseAuth's RLS-scoped client rather than an
// admin client, so an unauthorized student_id request fails at the RPC
// with a Postgres exception, not silently.
//
// Required Cloudflare Worker secret (set via `wrangler secret put`):
//   ANTHROPIC_API_KEY

import { createFileRoute } from "@tanstack/react-router";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

// Synthesis of a handful of already-computed numbers into a short readable
// summary — no reasoning-heavy task here, Haiku matches the ai-remark.ts
// cost/latency trade-off for a card that may reload every portal visit.
const MODEL = "claude-haiku-4-5-20251001";

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

export const Route = createFileRoute("/api/ai-learning-insight")({
  server: {
    middleware: [requireSupabaseAuth],
    handlers: {
      POST: async ({ request, context }) => {
        let body: { student_id?: string };
        try {
          body = await request.json();
        } catch {
          return jsonResponse({ error: "Bad JSON body" }, 400);
        }

        const { student_id } = body;
        if (!student_id || typeof student_id !== "string") {
          return jsonResponse({ error: "student_id is required" }, 400);
        }

        // RLS-scoped client (the requesting user's own bearer token) — see
        // header note above on why this must NOT be the admin client.
        const supabase = (context as any).supabase;

        const { data: ctxData, error: ctxErr } = await supabase.rpc("learning_ai_context", {
          _student_id: student_id,
        });
        if (ctxErr) {
          console.error("[ai-learning-insight] learning_ai_context failed:", ctxErr.message);
          const denied = /not authorized/i.test(ctxErr.message ?? "");
          return jsonResponse(
            { error: denied ? "Not authorized to view this student's learning context" : "Couldn't load learning context" },
            denied ? 403 : 500,
          );
        }

        const erp = ctxData?.erp_results ?? [];
        const mastery = ctxData?.learning_mastery ?? [];
        const recs = ctxData?.pending_recommendations ?? [];

        if (erp.length === 0 && mastery.length === 0) {
          return jsonResponse({
            narrative: "Not enough data yet — once there are some exam results or a few practice quizzes, insight will appear here.",
            actions: [],
          });
        }

        const apiKey = process.env.ANTHROPIC_API_KEY;
        if (!apiKey) {
          return jsonResponse(
            { error: "AI insight isn't configured yet — add the ANTHROPIC_API_KEY Cloudflare Worker secret." },
            503,
          );
        }

        const prompt = `You are helping a Kenyan school student (or their parent/teacher) understand their academic
picture by combining two SEPARATE data sources. Never imply these two sources are the same thing,
and never suggest changing, correcting or overriding either one — you are describing, not editing.

SOURCE 1 — Official ERP examination results (these are the real, final school records):
${JSON.stringify(erp, null, 2)}

SOURCE 2 — SmartDev Learning revision/practice performance (self-practice only, never an official exam):
${JSON.stringify(mastery, null, 2)}

Pending Learning recommendations already generated by the system:
${JSON.stringify(recs, null, 2)}

Write a short (3-5 sentence) plain-language narrative connecting the two sources — e.g. where revision
performance is strong/weak relative to official results, and what that might suggest. Then list up to 4
concrete, short (under 8 words each) suggested next actions a student could take (e.g. "Revise Algebra",
"Practice Ratio", "Take a mixed revision quiz").

Respond with ONLY raw JSON, no markdown fences, no preamble, in exactly this shape:
{"narrative": "...", "actions": ["...", "..."]}`;

        const anthropicRes = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "content-type": "application/json",
            "x-api-key": apiKey,
            "anthropic-version": "2023-06-01",
          },
          body: JSON.stringify({
            model: MODEL,
            max_tokens: 500,
            messages: [{ role: "user", content: prompt }],
          }),
        });

        if (!anthropicRes.ok) {
          const errText = await anthropicRes.text().catch(() => "");
          console.error("[ai-learning-insight] Anthropic API error:", anthropicRes.status, errText);
          let reason = "";
          try {
            reason = JSON.parse(errText)?.error?.message ?? "";
          } catch {
            reason = errText.slice(0, 300);
          }
          return jsonResponse(
            { error: reason ? `AI insight failed: ${reason}` : `AI insight failed (${anthropicRes.status})` },
            502,
          );
        }

        const data: any = await anthropicRes.json();
        const text = (data.content ?? []).find((b: any) => b.type === "text")?.text?.trim() ?? "";
        const clean = text.replace(/^```json\s*|```$/g, "").trim();

        let parsed: { narrative?: string; actions?: string[] };
        try {
          parsed = JSON.parse(clean);
        } catch {
          // Model didn't return clean JSON — fall back to showing the raw
          // text as the narrative rather than failing the whole card.
          return jsonResponse({ narrative: text || "No insight available right now.", actions: [] });
        }

        return jsonResponse({
          narrative: parsed.narrative ?? "No insight available right now.",
          actions: Array.isArray(parsed.actions) ? parsed.actions.slice(0, 4) : [],
        });
      },
    },
  },
});
