/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SysControlRoomRouteImport } from './routes/sys.control-room'
import { Route as PlatformSupportRouteImport } from './routes/platform.support'
import { Route as PlatformSchoolsRouteImport } from './routes/platform.schools'
import { Route as PlatformPlansRouteImport } from './routes/platform.plans'
import { Route as PlatformLoginRouteImport } from './routes/platform.login'
import { Route as PlatformInvoicesRouteImport } from './routes/platform.invoices'
import { Route as PlatformDashboardRouteImport } from './routes/platform.dashboard'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AppTransportRouteImport } from './routes/_app.transport'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppKitchenRouteImport } from './routes/_app.kitchen'
import { Route as AppDisciplineRouteImport } from './routes/_app.discipline'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClinicRouteImport } from './routes/_app.clinic'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppBoardingRouteImport } from './routes/_app.boarding'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as PlatformSchoolsIdRouteImport } from './routes/platform.schools.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa-callback'
import { Route as AppTimetableGenerateRouteImport } from './routes/_app.timetable.generate'
import { Route as AppPortalStudentRouteImport } from './routes/_app.portal.student'
import { Route as AppPortalParentRouteImport } from './routes/_app.portal.parent'
import { Route as AppIdsVerifyRouteImport } from './routes/_app.ids.verify'
import { Route as AppIdsBulkRouteImport } from './routes/_app.ids.bulk'
import { Route as AppFinancePaymentsRouteImport } from './routes/_app.finance.payments'
import { Route as AppFinanceInvoicesRouteImport } from './routes/_app.finance.invoices'
import { Route as AppFinanceGenerateRouteImport } from './routes/_app.finance.generate'
import { Route as AppFinanceFeesRouteImport } from './routes/_app.finance.fees'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminSchoolsRouteImport } from './routes/_app.admin.schools'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app.admin.permissions'
import { Route as AppAdminLinksRouteImport } from './routes/_app.admin.links'
import { Route as AppAdminImportRouteImport } from './routes/_app.admin.import'
import { Route as AppAdminBrainRouteImport } from './routes/_app.admin.brain'
import { Route as AppAdminActivityRouteImport } from './routes/_app.admin.activity'
import { Route as AppAcademicsSubjectsRouteImport } from './routes/_app.academics.subjects'
import { Route as AppAcademicsResultsRouteImport } from './routes/_app.academics.results'
import { Route as AppAcademicsReportCardsRouteImport } from './routes/_app.academics.report-cards'
import { Route as AppAcademicsMarksRouteImport } from './routes/_app.academics.marks'
import { Route as AppAcademicsExamsRouteImport } from './routes/_app.academics.exams'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppIdsStudentIdRouteImport } from './routes/_app.ids.student.$id'
import { Route as AppIdsStaffIdRouteImport } from './routes/_app.ids.staff.$id'
import { Route as AppFinanceReceiptIdRouteImport } from './routes/_app.finance.receipt.$id'
import { Route as AppAcademicsReportCardStudentIdExamIdRouteImport } from './routes/_app.academics.report-card.$studentId.$examId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SysControlRoomRoute = SysControlRoomRouteImport.update({
  id: '/sys/control-room',
  path: '/sys/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSchoolsRoute = PlatformSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformInvoicesRoute = PlatformInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplineRoute = AppDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicRoute = AppClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardingRoute = AppBoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const PlatformSchoolsIdRoute = PlatformSchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlatformSchoolsRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa-callback',
  path: '/api/public/mpesa-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimetableGenerateRoute = AppTimetableGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppTimetableRoute,
} as any)
const AppPortalStudentRoute = AppPortalStudentRouteImport.update({
  id: '/portal/student',
  path: '/portal/student',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalParentRoute = AppPortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppIdsVerifyRoute = AppIdsVerifyRouteImport.update({
  id: '/ids/verify',
  path: '/ids/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppIdsBulkRoute = AppIdsBulkRouteImport.update({
  id: '/ids/bulk',
  path: '/ids/bulk',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentsRoute = AppFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceGenerateRoute = AppFinanceGenerateRouteImport.update({
  id: '/finance/generate',
  path: '/finance/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceFeesRoute = AppFinanceFeesRouteImport.update({
  id: '/finance/fees',
  path: '/finance/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSchoolsRoute = AppAdminSchoolsRouteImport.update({
  id: '/admin/schools',
  path: '/admin/schools',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLinksRoute = AppAdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminImportRoute = AppAdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBrainRoute = AppAdminBrainRouteImport.update({
  id: '/admin/brain',
  path: '/admin/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsSubjectsRoute = AppAcademicsSubjectsRouteImport.update({
  id: '/academics/subjects',
  path: '/academics/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsResultsRoute = AppAcademicsResultsRouteImport.update({
  id: '/academics/results',
  path: '/academics/results',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsReportCardsRoute = AppAcademicsReportCardsRouteImport.update({
  id: '/academics/report-cards',
  path: '/academics/report-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsMarksRoute = AppAcademicsMarksRouteImport.update({
  id: '/academics/marks',
  path: '/academics/marks',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsExamsRoute = AppAcademicsExamsRouteImport.update({
  id: '/academics/exams',
  path: '/academics/exams',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIdsStudentIdRoute = AppIdsStudentIdRouteImport.update({
  id: '/ids/student/$id',
  path: '/ids/student/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIdsStaffIdRoute = AppIdsStaffIdRouteImport.update({
  id: '/ids/staff/$id',
  path: '/ids/staff/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReceiptIdRoute = AppFinanceReceiptIdRouteImport.update({
  id: '/finance/receipt/$id',
  path: '/finance/receipt/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsReportCardStudentIdExamIdRoute =
  AppAcademicsReportCardStudentIdExamIdRouteImport.update({
    id: '/academics/report-card/$studentId/$examId',
    path: '/academics/report-card/$studentId/$examId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/analytics': typeof AppAnalyticsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/boarding': typeof AppBoardingRoute
  '/classes': typeof AppClassesRoute
  '/clinic': typeof AppClinicRoute
  '/dashboard': typeof AppDashboardRoute
  '/discipline': typeof AppDisciplineRoute
  '/kitchen': typeof AppKitchenRoute
  '/library': typeof AppLibraryRoute
  '/security': typeof AppSecurityRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRouteWithChildren
  '/transport': typeof AppTransportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/invoices': typeof PlatformInvoicesRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/schools': typeof PlatformSchoolsRouteWithChildren
  '/platform/support': typeof PlatformSupportRoute
  '/sys/control-room': typeof SysControlRoomRoute
  '/academics/exams': typeof AppAcademicsExamsRoute
  '/academics/marks': typeof AppAcademicsMarksRoute
  '/academics/report-cards': typeof AppAcademicsReportCardsRoute
  '/academics/results': typeof AppAcademicsResultsRoute
  '/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/brain': typeof AppAdminBrainRoute
  '/admin/import': typeof AppAdminImportRoute
  '/admin/links': typeof AppAdminLinksRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/schools': typeof AppAdminSchoolsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/finance/fees': typeof AppFinanceFeesRoute
  '/finance/generate': typeof AppFinanceGenerateRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/ids/bulk': typeof AppIdsBulkRoute
  '/ids/verify': typeof AppIdsVerifyRoute
  '/portal/parent': typeof AppPortalParentRoute
  '/portal/student': typeof AppPortalStudentRoute
  '/timetable/generate': typeof AppTimetableGenerateRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/platform/schools/$id': typeof PlatformSchoolsIdRoute
  '/finance/receipt/$id': typeof AppFinanceReceiptIdRoute
  '/ids/staff/$id': typeof AppIdsStaffIdRoute
  '/ids/student/$id': typeof AppIdsStudentIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/academics/report-card/$studentId/$examId': typeof AppAcademicsReportCardStudentIdExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/analytics': typeof AppAnalyticsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/boarding': typeof AppBoardingRoute
  '/classes': typeof AppClassesRoute
  '/clinic': typeof AppClinicRoute
  '/dashboard': typeof AppDashboardRoute
  '/discipline': typeof AppDisciplineRoute
  '/kitchen': typeof AppKitchenRoute
  '/library': typeof AppLibraryRoute
  '/security': typeof AppSecurityRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRouteWithChildren
  '/transport': typeof AppTransportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/invoices': typeof PlatformInvoicesRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/schools': typeof PlatformSchoolsRouteWithChildren
  '/platform/support': typeof PlatformSupportRoute
  '/sys/control-room': typeof SysControlRoomRoute
  '/academics/exams': typeof AppAcademicsExamsRoute
  '/academics/marks': typeof AppAcademicsMarksRoute
  '/academics/report-cards': typeof AppAcademicsReportCardsRoute
  '/academics/results': typeof AppAcademicsResultsRoute
  '/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/brain': typeof AppAdminBrainRoute
  '/admin/import': typeof AppAdminImportRoute
  '/admin/links': typeof AppAdminLinksRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/schools': typeof AppAdminSchoolsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/finance/fees': typeof AppFinanceFeesRoute
  '/finance/generate': typeof AppFinanceGenerateRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/ids/bulk': typeof AppIdsBulkRoute
  '/ids/verify': typeof AppIdsVerifyRoute
  '/portal/parent': typeof AppPortalParentRoute
  '/portal/student': typeof AppPortalStudentRoute
  '/timetable/generate': typeof AppTimetableGenerateRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/platform/schools/$id': typeof PlatformSchoolsIdRoute
  '/finance/receipt/$id': typeof AppFinanceReceiptIdRoute
  '/ids/staff/$id': typeof AppIdsStaffIdRoute
  '/ids/student/$id': typeof AppIdsStudentIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/academics/report-card/$studentId/$examId': typeof AppAcademicsReportCardStudentIdExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/boarding': typeof AppBoardingRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/clinic': typeof AppClinicRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discipline': typeof AppDisciplineRoute
  '/_app/kitchen': typeof AppKitchenRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/timetable': typeof AppTimetableRouteWithChildren
  '/_app/transport': typeof AppTransportRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/invoices': typeof PlatformInvoicesRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/schools': typeof PlatformSchoolsRouteWithChildren
  '/platform/support': typeof PlatformSupportRoute
  '/sys/control-room': typeof SysControlRoomRoute
  '/_app/academics/exams': typeof AppAcademicsExamsRoute
  '/_app/academics/marks': typeof AppAcademicsMarksRoute
  '/_app/academics/report-cards': typeof AppAcademicsReportCardsRoute
  '/_app/academics/results': typeof AppAcademicsResultsRoute
  '/_app/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/brain': typeof AppAdminBrainRoute
  '/_app/admin/import': typeof AppAdminImportRoute
  '/_app/admin/links': typeof AppAdminLinksRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/schools': typeof AppAdminSchoolsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/finance/fees': typeof AppFinanceFeesRoute
  '/_app/finance/generate': typeof AppFinanceGenerateRoute
  '/_app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/_app/finance/payments': typeof AppFinancePaymentsRoute
  '/_app/ids/bulk': typeof AppIdsBulkRoute
  '/_app/ids/verify': typeof AppIdsVerifyRoute
  '/_app/portal/parent': typeof AppPortalParentRoute
  '/_app/portal/student': typeof AppPortalStudentRoute
  '/_app/timetable/generate': typeof AppTimetableGenerateRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/platform/schools/$id': typeof PlatformSchoolsIdRoute
  '/_app/finance/receipt/$id': typeof AppFinanceReceiptIdRoute
  '/_app/ids/staff/$id': typeof AppIdsStaffIdRoute
  '/_app/ids/student/$id': typeof AppIdsStudentIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_app/academics/report-card/$studentId/$examId': typeof AppAcademicsReportCardStudentIdExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/platform'
    | '/unsubscribe'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/boarding'
    | '/classes'
    | '/clinic'
    | '/dashboard'
    | '/discipline'
    | '/kitchen'
    | '/library'
    | '/security'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/email/unsubscribe'
    | '/platform/dashboard'
    | '/platform/invoices'
    | '/platform/login'
    | '/platform/plans'
    | '/platform/schools'
    | '/platform/support'
    | '/sys/control-room'
    | '/academics/exams'
    | '/academics/marks'
    | '/academics/report-cards'
    | '/academics/results'
    | '/academics/subjects'
    | '/admin/activity'
    | '/admin/brain'
    | '/admin/import'
    | '/admin/links'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/users'
    | '/finance/fees'
    | '/finance/generate'
    | '/finance/invoices'
    | '/finance/payments'
    | '/ids/bulk'
    | '/ids/verify'
    | '/portal/parent'
    | '/portal/student'
    | '/timetable/generate'
    | '/api/public/mpesa-callback'
    | '/lovable/email/suppression'
    | '/platform/schools/$id'
    | '/finance/receipt/$id'
    | '/ids/staff/$id'
    | '/ids/student/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/academics/report-card/$studentId/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/platform'
    | '/unsubscribe'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/boarding'
    | '/classes'
    | '/clinic'
    | '/dashboard'
    | '/discipline'
    | '/kitchen'
    | '/library'
    | '/security'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/email/unsubscribe'
    | '/platform/dashboard'
    | '/platform/invoices'
    | '/platform/login'
    | '/platform/plans'
    | '/platform/schools'
    | '/platform/support'
    | '/sys/control-room'
    | '/academics/exams'
    | '/academics/marks'
    | '/academics/report-cards'
    | '/academics/results'
    | '/academics/subjects'
    | '/admin/activity'
    | '/admin/brain'
    | '/admin/import'
    | '/admin/links'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/users'
    | '/finance/fees'
    | '/finance/generate'
    | '/finance/invoices'
    | '/finance/payments'
    | '/ids/bulk'
    | '/ids/verify'
    | '/portal/parent'
    | '/portal/student'
    | '/timetable/generate'
    | '/api/public/mpesa-callback'
    | '/lovable/email/suppression'
    | '/platform/schools/$id'
    | '/finance/receipt/$id'
    | '/ids/staff/$id'
    | '/ids/student/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/academics/report-card/$studentId/$examId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/platform'
    | '/unsubscribe'
    | '/_app/analytics'
    | '/_app/announcements'
    | '/_app/attendance'
    | '/_app/boarding'
    | '/_app/classes'
    | '/_app/clinic'
    | '/_app/dashboard'
    | '/_app/discipline'
    | '/_app/kitchen'
    | '/_app/library'
    | '/_app/security'
    | '/_app/staff'
    | '/_app/students'
    | '/_app/timetable'
    | '/_app/transport'
    | '/email/unsubscribe'
    | '/platform/dashboard'
    | '/platform/invoices'
    | '/platform/login'
    | '/platform/plans'
    | '/platform/schools'
    | '/platform/support'
    | '/sys/control-room'
    | '/_app/academics/exams'
    | '/_app/academics/marks'
    | '/_app/academics/report-cards'
    | '/_app/academics/results'
    | '/_app/academics/subjects'
    | '/_app/admin/activity'
    | '/_app/admin/brain'
    | '/_app/admin/import'
    | '/_app/admin/links'
    | '/_app/admin/permissions'
    | '/_app/admin/roles'
    | '/_app/admin/schools'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/finance/fees'
    | '/_app/finance/generate'
    | '/_app/finance/invoices'
    | '/_app/finance/payments'
    | '/_app/ids/bulk'
    | '/_app/ids/verify'
    | '/_app/portal/parent'
    | '/_app/portal/student'
    | '/_app/timetable/generate'
    | '/api/public/mpesa-callback'
    | '/lovable/email/suppression'
    | '/platform/schools/$id'
    | '/_app/finance/receipt/$id'
    | '/_app/ids/staff/$id'
    | '/_app/ids/student/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_app/academics/report-card/$studentId/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SysControlRoomRoute: typeof SysControlRoomRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys/control-room': {
      id: '/sys/control-room'
      path: '/sys/control-room'
      fullPath: '/sys/control-room'
      preLoaderRoute: typeof SysControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/support': {
      id: '/platform/support'
      path: '/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof PlatformSupportRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/schools': {
      id: '/platform/schools'
      path: '/schools'
      fullPath: '/platform/schools'
      preLoaderRoute: typeof PlatformSchoolsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/plans': {
      id: '/platform/plans'
      path: '/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/invoices': {
      id: '/platform/invoices'
      path: '/invoices'
      fullPath: '/platform/invoices'
      preLoaderRoute: typeof PlatformInvoicesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transport': {
      id: '/_app/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kitchen': {
      id: '/_app/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discipline': {
      id: '/_app/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof AppDisciplineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinic': {
      id: '/_app/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof AppClinicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boarding': {
      id: '/_app/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof AppBoardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform/schools/$id': {
      id: '/platform/schools/$id'
      path: '/$id'
      fullPath: '/platform/schools/$id'
      preLoaderRoute: typeof PlatformSchoolsIdRouteImport
      parentRoute: typeof PlatformSchoolsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa-callback': {
      id: '/api/public/mpesa-callback'
      path: '/api/public/mpesa-callback'
      fullPath: '/api/public/mpesa-callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timetable/generate': {
      id: '/_app/timetable/generate'
      path: '/generate'
      fullPath: '/timetable/generate'
      preLoaderRoute: typeof AppTimetableGenerateRouteImport
      parentRoute: typeof AppTimetableRoute
    }
    '/_app/portal/student': {
      id: '/_app/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof AppPortalStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/parent': {
      id: '/_app/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof AppPortalParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ids/verify': {
      id: '/_app/ids/verify'
      path: '/ids/verify'
      fullPath: '/ids/verify'
      preLoaderRoute: typeof AppIdsVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ids/bulk': {
      id: '/_app/ids/bulk'
      path: '/ids/bulk'
      fullPath: '/ids/bulk'
      preLoaderRoute: typeof AppIdsBulkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/payments': {
      id: '/_app/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AppFinancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/invoices': {
      id: '/_app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/generate': {
      id: '/_app/finance/generate'
      path: '/finance/generate'
      fullPath: '/finance/generate'
      preLoaderRoute: typeof AppFinanceGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/fees': {
      id: '/_app/finance/fees'
      path: '/finance/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof AppFinanceFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/schools': {
      id: '/_app/admin/schools'
      path: '/admin/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AppAdminSchoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/links': {
      id: '/_app/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AppAdminLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/import': {
      id: '/_app/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AppAdminImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/brain': {
      id: '/_app/admin/brain'
      path: '/admin/brain'
      fullPath: '/admin/brain'
      preLoaderRoute: typeof AppAdminBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/subjects': {
      id: '/_app/academics/subjects'
      path: '/academics/subjects'
      fullPath: '/academics/subjects'
      preLoaderRoute: typeof AppAcademicsSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/results': {
      id: '/_app/academics/results'
      path: '/academics/results'
      fullPath: '/academics/results'
      preLoaderRoute: typeof AppAcademicsResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/report-cards': {
      id: '/_app/academics/report-cards'
      path: '/academics/report-cards'
      fullPath: '/academics/report-cards'
      preLoaderRoute: typeof AppAcademicsReportCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/marks': {
      id: '/_app/academics/marks'
      path: '/academics/marks'
      fullPath: '/academics/marks'
      preLoaderRoute: typeof AppAcademicsMarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/exams': {
      id: '/_app/academics/exams'
      path: '/academics/exams'
      fullPath: '/academics/exams'
      preLoaderRoute: typeof AppAcademicsExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ids/student/$id': {
      id: '/_app/ids/student/$id'
      path: '/ids/student/$id'
      fullPath: '/ids/student/$id'
      preLoaderRoute: typeof AppIdsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ids/staff/$id': {
      id: '/_app/ids/staff/$id'
      path: '/ids/staff/$id'
      fullPath: '/ids/staff/$id'
      preLoaderRoute: typeof AppIdsStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/receipt/$id': {
      id: '/_app/finance/receipt/$id'
      path: '/finance/receipt/$id'
      fullPath: '/finance/receipt/$id'
      preLoaderRoute: typeof AppFinanceReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/report-card/$studentId/$examId': {
      id: '/_app/academics/report-card/$studentId/$examId'
      path: '/academics/report-card/$studentId/$examId'
      fullPath: '/academics/report-card/$studentId/$examId'
      preLoaderRoute: typeof AppAcademicsReportCardStudentIdExamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTimetableRouteChildren {
  AppTimetableGenerateRoute: typeof AppTimetableGenerateRoute
}

const AppTimetableRouteChildren: AppTimetableRouteChildren = {
  AppTimetableGenerateRoute: AppTimetableGenerateRoute,
}

const AppTimetableRouteWithChildren = AppTimetableRoute._addFileChildren(
  AppTimetableRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBoardingRoute: typeof AppBoardingRoute
  AppClassesRoute: typeof AppClassesRoute
  AppClinicRoute: typeof AppClinicRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisciplineRoute: typeof AppDisciplineRoute
  AppKitchenRoute: typeof AppKitchenRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTimetableRoute: typeof AppTimetableRouteWithChildren
  AppTransportRoute: typeof AppTransportRoute
  AppAcademicsExamsRoute: typeof AppAcademicsExamsRoute
  AppAcademicsMarksRoute: typeof AppAcademicsMarksRoute
  AppAcademicsReportCardsRoute: typeof AppAcademicsReportCardsRoute
  AppAcademicsResultsRoute: typeof AppAcademicsResultsRoute
  AppAcademicsSubjectsRoute: typeof AppAcademicsSubjectsRoute
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminBrainRoute: typeof AppAdminBrainRoute
  AppAdminImportRoute: typeof AppAdminImportRoute
  AppAdminLinksRoute: typeof AppAdminLinksRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSchoolsRoute: typeof AppAdminSchoolsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppFinanceFeesRoute: typeof AppFinanceFeesRoute
  AppFinanceGenerateRoute: typeof AppFinanceGenerateRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinancePaymentsRoute: typeof AppFinancePaymentsRoute
  AppIdsBulkRoute: typeof AppIdsBulkRoute
  AppIdsVerifyRoute: typeof AppIdsVerifyRoute
  AppPortalParentRoute: typeof AppPortalParentRoute
  AppPortalStudentRoute: typeof AppPortalStudentRoute
  AppFinanceReceiptIdRoute: typeof AppFinanceReceiptIdRoute
  AppIdsStaffIdRoute: typeof AppIdsStaffIdRoute
  AppIdsStudentIdRoute: typeof AppIdsStudentIdRoute
  AppAcademicsReportCardStudentIdExamIdRoute: typeof AppAcademicsReportCardStudentIdExamIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBoardingRoute: AppBoardingRoute,
  AppClassesRoute: AppClassesRoute,
  AppClinicRoute: AppClinicRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisciplineRoute: AppDisciplineRoute,
  AppKitchenRoute: AppKitchenRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppStaffRoute: AppStaffRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTimetableRoute: AppTimetableRouteWithChildren,
  AppTransportRoute: AppTransportRoute,
  AppAcademicsExamsRoute: AppAcademicsExamsRoute,
  AppAcademicsMarksRoute: AppAcademicsMarksRoute,
  AppAcademicsReportCardsRoute: AppAcademicsReportCardsRoute,
  AppAcademicsResultsRoute: AppAcademicsResultsRoute,
  AppAcademicsSubjectsRoute: AppAcademicsSubjectsRoute,
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminBrainRoute: AppAdminBrainRoute,
  AppAdminImportRoute: AppAdminImportRoute,
  AppAdminLinksRoute: AppAdminLinksRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSchoolsRoute: AppAdminSchoolsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppFinanceFeesRoute: AppFinanceFeesRoute,
  AppFinanceGenerateRoute: AppFinanceGenerateRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinancePaymentsRoute: AppFinancePaymentsRoute,
  AppIdsBulkRoute: AppIdsBulkRoute,
  AppIdsVerifyRoute: AppIdsVerifyRoute,
  AppPortalParentRoute: AppPortalParentRoute,
  AppPortalStudentRoute: AppPortalStudentRoute,
  AppFinanceReceiptIdRoute: AppFinanceReceiptIdRoute,
  AppIdsStaffIdRoute: AppIdsStaffIdRoute,
  AppIdsStudentIdRoute: AppIdsStudentIdRoute,
  AppAcademicsReportCardStudentIdExamIdRoute:
    AppAcademicsReportCardStudentIdExamIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformSchoolsRouteChildren {
  PlatformSchoolsIdRoute: typeof PlatformSchoolsIdRoute
}

const PlatformSchoolsRouteChildren: PlatformSchoolsRouteChildren = {
  PlatformSchoolsIdRoute: PlatformSchoolsIdRoute,
}

const PlatformSchoolsRouteWithChildren = PlatformSchoolsRoute._addFileChildren(
  PlatformSchoolsRouteChildren,
)

interface PlatformRouteChildren {
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformInvoicesRoute: typeof PlatformInvoicesRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformSchoolsRoute: typeof PlatformSchoolsRouteWithChildren
  PlatformSupportRoute: typeof PlatformSupportRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformInvoicesRoute: PlatformInvoicesRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  PlatformPlansRoute: PlatformPlansRoute,
  PlatformSchoolsRoute: PlatformSchoolsRouteWithChildren,
  PlatformSupportRoute: PlatformSupportRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SysControlRoomRoute: SysControlRoomRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
