/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransportRouteImport } from './routes/_app.transport'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppDisciplineRouteImport } from './routes/_app.discipline'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClinicRouteImport } from './routes/_app.clinic'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppBoardingRouteImport } from './routes/_app.boarding'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa-callback'
import { Route as AppPortalStudentRouteImport } from './routes/_app.portal.student'
import { Route as AppPortalParentRouteImport } from './routes/_app.portal.parent'
import { Route as AppFinancePaymentsRouteImport } from './routes/_app.finance.payments'
import { Route as AppFinanceInvoicesRouteImport } from './routes/_app.finance.invoices'
import { Route as AppFinanceGenerateRouteImport } from './routes/_app.finance.generate'
import { Route as AppFinanceFeesRouteImport } from './routes/_app.finance.fees'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminLinksRouteImport } from './routes/_app.admin.links'
import { Route as AppAdminActivityRouteImport } from './routes/_app.admin.activity'
import { Route as AppAcademicsSubjectsRouteImport } from './routes/_app.academics.subjects'
import { Route as AppAcademicsResultsRouteImport } from './routes/_app.academics.results'
import { Route as AppAcademicsExamsRouteImport } from './routes/_app.academics.exams'
import { Route as AppFinanceReceiptIdRouteImport } from './routes/_app.finance.receipt.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplineRoute = AppDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicRoute = AppClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardingRoute = AppBoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa-callback',
  path: '/api/public/mpesa-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPortalStudentRoute = AppPortalStudentRouteImport.update({
  id: '/portal/student',
  path: '/portal/student',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalParentRoute = AppPortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentsRoute = AppFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceGenerateRoute = AppFinanceGenerateRouteImport.update({
  id: '/finance/generate',
  path: '/finance/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceFeesRoute = AppFinanceFeesRouteImport.update({
  id: '/finance/fees',
  path: '/finance/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLinksRoute = AppAdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsSubjectsRoute = AppAcademicsSubjectsRouteImport.update({
  id: '/academics/subjects',
  path: '/academics/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsResultsRoute = AppAcademicsResultsRouteImport.update({
  id: '/academics/results',
  path: '/academics/results',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsExamsRoute = AppAcademicsExamsRouteImport.update({
  id: '/academics/exams',
  path: '/academics/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReceiptIdRoute = AppFinanceReceiptIdRouteImport.update({
  id: '/finance/receipt/$id',
  path: '/finance/receipt/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/boarding': typeof AppBoardingRoute
  '/classes': typeof AppClassesRoute
  '/clinic': typeof AppClinicRoute
  '/dashboard': typeof AppDashboardRoute
  '/discipline': typeof AppDisciplineRoute
  '/library': typeof AppLibraryRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/transport': typeof AppTransportRoute
  '/academics/exams': typeof AppAcademicsExamsRoute
  '/academics/results': typeof AppAcademicsResultsRoute
  '/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/links': typeof AppAdminLinksRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/finance/fees': typeof AppFinanceFeesRoute
  '/finance/generate': typeof AppFinanceGenerateRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/portal/parent': typeof AppPortalParentRoute
  '/portal/student': typeof AppPortalStudentRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/finance/receipt/$id': typeof AppFinanceReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/boarding': typeof AppBoardingRoute
  '/classes': typeof AppClassesRoute
  '/clinic': typeof AppClinicRoute
  '/dashboard': typeof AppDashboardRoute
  '/discipline': typeof AppDisciplineRoute
  '/library': typeof AppLibraryRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRoute
  '/timetable': typeof AppTimetableRoute
  '/transport': typeof AppTransportRoute
  '/academics/exams': typeof AppAcademicsExamsRoute
  '/academics/results': typeof AppAcademicsResultsRoute
  '/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/links': typeof AppAdminLinksRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/finance/fees': typeof AppFinanceFeesRoute
  '/finance/generate': typeof AppFinanceGenerateRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/portal/parent': typeof AppPortalParentRoute
  '/portal/student': typeof AppPortalStudentRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/finance/receipt/$id': typeof AppFinanceReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/boarding': typeof AppBoardingRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/clinic': typeof AppClinicRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discipline': typeof AppDisciplineRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/transport': typeof AppTransportRoute
  '/_app/academics/exams': typeof AppAcademicsExamsRoute
  '/_app/academics/results': typeof AppAcademicsResultsRoute
  '/_app/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/links': typeof AppAdminLinksRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/finance/fees': typeof AppFinanceFeesRoute
  '/_app/finance/generate': typeof AppFinanceGenerateRoute
  '/_app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/_app/finance/payments': typeof AppFinancePaymentsRoute
  '/_app/portal/parent': typeof AppPortalParentRoute
  '/_app/portal/student': typeof AppPortalStudentRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/_app/finance/receipt/$id': typeof AppFinanceReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/attendance'
    | '/boarding'
    | '/classes'
    | '/clinic'
    | '/dashboard'
    | '/discipline'
    | '/library'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/academics/exams'
    | '/academics/results'
    | '/academics/subjects'
    | '/admin/activity'
    | '/admin/links'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/finance/fees'
    | '/finance/generate'
    | '/finance/invoices'
    | '/finance/payments'
    | '/portal/parent'
    | '/portal/student'
    | '/api/public/mpesa-callback'
    | '/finance/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/announcements'
    | '/attendance'
    | '/boarding'
    | '/classes'
    | '/clinic'
    | '/dashboard'
    | '/discipline'
    | '/library'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/academics/exams'
    | '/academics/results'
    | '/academics/subjects'
    | '/admin/activity'
    | '/admin/links'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/finance/fees'
    | '/finance/generate'
    | '/finance/invoices'
    | '/finance/payments'
    | '/portal/parent'
    | '/portal/student'
    | '/api/public/mpesa-callback'
    | '/finance/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/announcements'
    | '/_app/attendance'
    | '/_app/boarding'
    | '/_app/classes'
    | '/_app/clinic'
    | '/_app/dashboard'
    | '/_app/discipline'
    | '/_app/library'
    | '/_app/staff'
    | '/_app/students'
    | '/_app/timetable'
    | '/_app/transport'
    | '/_app/academics/exams'
    | '/_app/academics/results'
    | '/_app/academics/subjects'
    | '/_app/admin/activity'
    | '/_app/admin/links'
    | '/_app/admin/roles'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/finance/fees'
    | '/_app/finance/generate'
    | '/_app/finance/invoices'
    | '/_app/finance/payments'
    | '/_app/portal/parent'
    | '/_app/portal/student'
    | '/api/public/mpesa-callback'
    | '/_app/finance/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transport': {
      id: '/_app/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discipline': {
      id: '/_app/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof AppDisciplineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinic': {
      id: '/_app/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof AppClinicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boarding': {
      id: '/_app/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof AppBoardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/mpesa-callback': {
      id: '/api/public/mpesa-callback'
      path: '/api/public/mpesa-callback'
      fullPath: '/api/public/mpesa-callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/portal/student': {
      id: '/_app/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof AppPortalStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/parent': {
      id: '/_app/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof AppPortalParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/payments': {
      id: '/_app/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AppFinancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/invoices': {
      id: '/_app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/generate': {
      id: '/_app/finance/generate'
      path: '/finance/generate'
      fullPath: '/finance/generate'
      preLoaderRoute: typeof AppFinanceGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/fees': {
      id: '/_app/finance/fees'
      path: '/finance/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof AppFinanceFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/links': {
      id: '/_app/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AppAdminLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/subjects': {
      id: '/_app/academics/subjects'
      path: '/academics/subjects'
      fullPath: '/academics/subjects'
      preLoaderRoute: typeof AppAcademicsSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/results': {
      id: '/_app/academics/results'
      path: '/academics/results'
      fullPath: '/academics/results'
      preLoaderRoute: typeof AppAcademicsResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics/exams': {
      id: '/_app/academics/exams'
      path: '/academics/exams'
      fullPath: '/academics/exams'
      preLoaderRoute: typeof AppAcademicsExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/receipt/$id': {
      id: '/_app/finance/receipt/$id'
      path: '/finance/receipt/$id'
      fullPath: '/finance/receipt/$id'
      preLoaderRoute: typeof AppFinanceReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBoardingRoute: typeof AppBoardingRoute
  AppClassesRoute: typeof AppClassesRoute
  AppClinicRoute: typeof AppClinicRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisciplineRoute: typeof AppDisciplineRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppTransportRoute: typeof AppTransportRoute
  AppAcademicsExamsRoute: typeof AppAcademicsExamsRoute
  AppAcademicsResultsRoute: typeof AppAcademicsResultsRoute
  AppAcademicsSubjectsRoute: typeof AppAcademicsSubjectsRoute
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminLinksRoute: typeof AppAdminLinksRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppFinanceFeesRoute: typeof AppFinanceFeesRoute
  AppFinanceGenerateRoute: typeof AppFinanceGenerateRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinancePaymentsRoute: typeof AppFinancePaymentsRoute
  AppPortalParentRoute: typeof AppPortalParentRoute
  AppPortalStudentRoute: typeof AppPortalStudentRoute
  AppFinanceReceiptIdRoute: typeof AppFinanceReceiptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBoardingRoute: AppBoardingRoute,
  AppClassesRoute: AppClassesRoute,
  AppClinicRoute: AppClinicRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisciplineRoute: AppDisciplineRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppStaffRoute: AppStaffRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppTransportRoute: AppTransportRoute,
  AppAcademicsExamsRoute: AppAcademicsExamsRoute,
  AppAcademicsResultsRoute: AppAcademicsResultsRoute,
  AppAcademicsSubjectsRoute: AppAcademicsSubjectsRoute,
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminLinksRoute: AppAdminLinksRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppFinanceFeesRoute: AppFinanceFeesRoute,
  AppFinanceGenerateRoute: AppFinanceGenerateRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinancePaymentsRoute: AppFinancePaymentsRoute,
  AppPortalParentRoute: AppPortalParentRoute,
  AppPortalStudentRoute: AppPortalStudentRoute,
  AppFinanceReceiptIdRoute: AppFinanceReceiptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
