// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getSessionSafe } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Uses getSessionSafe() rather than a raw `supabase.auth.getSession()` — see
// the full explanation in client.ts. This middleware runs in front of EVERY
// server function call in the app (21+ routes use useServerFn), so an
// unguarded hang here doesn't just freeze one page load, it silently freezes
// any button/action anywhere that goes through a server fn: no request ever
// fires, nothing throws, nothing logs. On timeout we proceed without a
// bearer token rather than hang — the server fn will simply come back
// unauthenticated/401 instead of never coming back at all, which is
// recoverable (retry, re-login) where an infinite hang isn't.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await getSessionSafe()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
